spring.application.name=checkmate-backend
# Change the server port to 8081
server.port=8081
# Enable pretty JSON output
spring.jackson.serialization.indent-output=true
# only update DB schema (keep existing data)
spring.jpa.hibernate.ddl-auto=update

# === Auth0 / OAuth2 Resource Server (Iteration 13b) ===
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-a2xkmhnunpsikb72.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audience=https://checkmate.api

spring.jpa.hibernate.ddl-auto=update